In [1]:
# list comprehension example

numbers = [1, 2, 3, 4]
squares = [n**2 for n in numbers]

print(squares)  # Output: [1, 4, 9, 16]

[1, 4, 9, 16]


In [2]:
# list comprehension vs. generator expression 

listcomp = ['Hello' for i in range(3)]
genexpr = ('Hello' for i in range(3))

In [112]:
listcomp


['Hello', 'Hello', 'Hello']

## Listcomps

In [3]:
symbols = '$#@$%&'
beyound_ascii = [ord(s) for s in symbols if ord(s)>127]
beyound_ascii

[]

In [4]:
beyound_ascii = list(filter(lambda c: c>127, map(ord,symbols)))
beyound_ascii

[]

**Example 2-4. Cartesian product using list comprehension ( produce a list of T-shirt available in two colors and three sizes)

In [11]:
colors = ['black','white']
sizes = ['S','M','L']

tshirts = [(color, size) for color in colors for size in sizes]
tshirts
# This generates a list of tuples arranged by color, then size 

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [7]:
for color in colors:
    for size in sizes:
        print((color,size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [14]:
# Size, then color
tshirts = [(size,color) for size in sizes for color in colors]
tshirts

[('S', 'black'),
 ('S', 'white'),
 ('M', 'black'),
 ('M', 'white'),
 ('L', 'black'),
 ('L', 'white')]

## Generator Expression 

**Example 2-5. Initializing a tuple and an array from a generator expression.

In [15]:
symbols = '@#$%&'
tuple(ord(symbol) for symbol in symbols) 
# If the generator expression is the single argument in a function call, 
# there is no need to duplicate the enclosing parentheses 

(64, 35, 36, 37, 38)

In [16]:
# The array constructor takes two arguments, so the parentheses around the 
# generator expression are mandatory 
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [64, 35, 36, 37, 38])

**Example 2-6: Cartesian product in a generator expression 

In [17]:
colors = ['black','white']
sizes = ['S','M','L']

for tshirts in ('%s %s'% (c,s) for c in colors for s in sizes):
    print(tshirts)

black S
black M
black L
white S
white M
white L


## Tuples

**Example 2-7. Tuples used as records

In [23]:
lax_coordinates = (33.9425, -118.408056)

city,year,pop,chg,area=('Tokyo', 2003, 32450, 0.66, 8014)

traveler_ids = [('USA','31195855'),('BRA','CE342567'), ('ESP','XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [21]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


### Tuple unpakcing: parallel assignment

In [25]:
# Most visible form of tuple unpacking: Parallel assignment 

lax_coordinates = (33.9425, -118.408056)

latitude, longitude = lax_coordinates # tuple unpacking
latitude

33.9425

In [29]:
# Prefixing an argument with a star when calling a function 

divmod(20,8) #return (2,4)
t=(20,8)
divmod(*t)

quotient,remainder = divmod(*t) # prefix an argument 
quotient,remainder

(2, 4)

In [31]:
# Use * to grab excess items.
# In the context of parallel assignment, the * prefix can be applied to 
# exactly one variable, but it can appear in any position. 

a,b,*rest=range(5)
a,b,rest

(0, 1, [2, 3, 4])

In [32]:
a,b,*rest=range(3)
a,b,rest

(0, 1, [2])

In [34]:
a,b,*rest=range(2)
a,b,rest

(0, 1, [])

In [37]:
a,*body,c,d = range(5)
a,body,c,d

(0, [1, 2], 3, 4)

In [38]:
*head,b,c,d = range(5)
head, b,c,d

([0, 1], 2, 3, 4)

### Nested tuple unpacking

**Example 2-8. Unpacking nested tuples to access the longitude

In [45]:
metro_areas = [
    ('Tokyo','JP',36.933,(35.689722,139.691667)),
    ('Delhi NCR', 'IN', 21.935,(28.613889,77.208899)),
    ('Mexico City','MX',20.142,(19.433333,-99.133333)),
    ('New York-Newwark','US',20.104,(40.808611,-74.020386)),
    ('Sao Paulo','BR',19.649,(-23.547778,-46.635833)),
]

print('{:15}|{:^9}|{:^9}'.format('','lat.','long.'))


               |  lat.   |  long.  


In [46]:
fmt = '{:15}|{:9.4f}|{:^9.4f}'

for name,cc,pop,(latitude,longitude) in metro_areas:
    if longitude <=0:
        print(fmt.format(name,latitude,longitude))

Mexico City    |  19.4333|-99.1333 
New York-Newwark|  40.8086|-74.0204 
Sao Paulo      | -23.5478|-46.6358 


### Named tuples

**Example 2-9. Defining and using a named tuple type. It shows how we could define a named tuple to hold information about a city 

In [48]:
from collections import namedtuple 

City = namedtuple('City','named country population coordiantes') # Two 
# parameters are required to create a named tuple: a class name and a list/
# fild name 

tokyo = City('Tokyo','JP',36.933, (35.689722, 139.691667))

tokyo

City(named='Tokyo', country='JP', population=36.933, coordiantes=(35.689722, 139.691667))

In [49]:
tokyo.coordiantes

(35.689722, 139.691667)

In [50]:
tokyo[1]

'JP'

**Example 2-10. Named tuple attributes and methods. It shows the most useful: the _fields class attribute, the class method _make(iterable), and the _asdict() instance method. 

In [55]:
City._fields #_fields is a tuple with the field names of the class
('name','country','population','coordinates')

LatLong = namedtuple('LatLong','lat long')

delhi_data = ('Delhi NCR','IN',21.935, LatLong(28.613889,77.208889))

delhi = City._make(delhi_data)# _make allow us to instantiate a named tuple
# from an iterable

delhi._asdict() #store info as dictionary 

City(named='Delhi NCR', country='IN', population=21.935, coordiantes=LatLong(lat=28.613889, long=77.208889))

In [54]:
for key,value in delhi._asdict().items():
    print(key + ':', value)

named: Delhi NCR
country: IN
population: 21.935
coordiantes: LatLong(lat=28.613889, long=77.208889)


## Slicing

In [57]:
l =[10,20,30,40,50,60]
l[:2] # split at 2

[10, 20]

In [58]:
s = 'bicycle'
s[::3] #[start:stop:step]

'bye'

### Assigning to slices

In [59]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
l[2:5]=[20,30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [61]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [62]:
l[3::2]=[11,12]
l

[0, 1, 20, 11, 5, 12, 9]

### Using + and * with sequences

In [63]:
l=[1,2,3]
l*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [64]:
5*'abcd' # Both + and * create a new object and never change their operands

'abcdabcdabcdabcdabcd'

### Building lists of lists

**Example 2-12. A list with 3 lists of length 3 can represent a tic-tac-toe board

In [67]:
# Create a list of 3 lists of 3 items each 
board = [['_']*3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [68]:
board[1][2] ='X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [70]:
weird_board=[['_']*3]*3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [71]:
# All rows are aliases referring to the same object 
weird_board[1][2] ='O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

### Augmented assginment with sequences

In [72]:
l = [1,2,3]
id(l)  # ID of the initial list

140584482986560

In [77]:
l *=2
l
id(l) # After multiplication, the list is the same object

140584482986560

In [75]:
t=(1,2,3)
id(t) # ID of the initial tuple 

140584483194752

In [76]:
t *=2
id(t) # After multiplication, a new tuple was created 

140584483032704

### list.sort and the sorted Built-in Function 

In [80]:
fruits = ['grape','raspberry','apple','banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [81]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [83]:
sorted(fruits,key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [84]:
fruits # The original dataset doesn't change 

['grape', 'raspberry', 'apple', 'banana']

In [86]:
fruits.sort() # Now the original list is sorted 
fruits

['apple', 'banana', 'grape', 'raspberry']

### Managing ordered sequences with bisect

**Example 2-17. bisect finds insertion 

In [87]:
import bisect 
import sys

In [90]:
HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'


In [91]:
def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)  # Use the bisect function 
        # to get the insertion point 
        offset = position * '  |'  # Build a pattern of vertical bars 
        # proportional to the offset 
        print(ROW_FMT.format(needle, position, offset))  # Print formatted 
        # row showing needle and insertion point

if __name__ == '__main__':

    if sys.argv[-1] == 'left':    # Choose the bisect function to use 
        #according to the last command-line argument 
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect

    print('DEMO:', bisect_fn.__name__)  
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)


DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


**Example 2-18. Given a test score, grade returns the corresponding letter grade 

In [98]:
def grade(score, breakpoints=[60,70,80,90], grades='FDCBA'):
    i = bisect.bisect(breakpoints,score)
    return grades[i]

In [102]:
[grade(score) for score in [33,99,77,70,89,90,100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

**Example 2-19. Insort keeps a sorted sequence always sorted 

In [103]:
import bisect 
import random 

In [104]:
SIZE = 7
random.seed(1729)

In [108]:
my_list = []

for i in range(SIZE):
    
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    
    print('%2d ->'% new_item, my_list)

 4 -> [4]
 3 -> [3, 4]
13 -> [3, 4, 13]
 2 -> [2, 3, 4, 13]
13 -> [2, 3, 4, 13, 13]
11 -> [2, 3, 4, 11, 13, 13]
 8 -> [2, 3, 4, 8, 11, 13, 13]


### Arrays

**Example 2-20: Creating, saving, and loading a large array of floats

In [110]:
from array import array
from random import random

In [111]:
# Create an array of double-precision floats (typecode'd')

floats = array('d', (random() for i in range(10**7)))

In [113]:
floats[-1]

0.24105285838870494

In [118]:
fp = open('floats.bin','wb')
floats.tofile(fp) # Write all items (as machine values) to the file object fp.
fp.close()

In [119]:
floats2 = array('d')
fp = open('floats.bin','rb')

In [120]:
floats2.fromfile(fp,10**7)
# Read n items (as machine values) from the file 
# and append them to the end of the array.
fp.close()
floats2[-1]

0.24105285838870494

In [121]:
floats2 == floats

True

### Memory Views

**Example 2-21. Changing the value of an array item by poking one of its bytes

In [123]:
numbers = array('h',[-2,-1,0,1,2])
memv = memoryview(numbers)

In [124]:
len(memv)

5

In [125]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [126]:
memv_oct[5] = 4

In [127]:
numbers

array('h', [-2, -1, 1024, 1, 2])

### Numpy and SciPy

**Example2-22. Basic operations with rows and columns in a numpy.ndarray

In [129]:
import numpy as np

In [130]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [132]:
type(a)

numpy.ndarray

In [133]:
a.shape

(12,)

In [136]:
a.shape = (3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
a[2]

array([ 8,  9, 10, 11])

In [138]:
a[2,1]

9

In [139]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Deques and Other Queues

**Example 2-23. Working with a deque

In [140]:
from collections import deque

In [141]:
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [144]:
dq.rotate(-4)
dq

deque([5, 6, 7, 8, 9, 0, 1, 2, 3, 4])

In [145]:
dq.appendleft(-1)
dq

deque([-1, 5, 6, 7, 8, 9, 0, 1, 2, 3])

In [147]:
dq.extend([11,22,33]) # Adding 3 items to the right pushes out the leftmost 
# -1,1,and 2
dq

deque([10, -1, 5, 6, 7, 8, 9, 11, 22, 33])

In [146]:
dq.extendleft([10,20,30,40]) #
dq

deque([40, 30, 20, 10, -1, 5, 6, 7, 8, 9])